/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Comment = IDL.Record({
  'tokenId' : IDL.Nat,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const Token = IDL.Record({
  'id' : IDL.Nat,
  'creator' : IDL.Principal,
  'ticker' : IDL.Text,
  'tokenSupply' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'icpReserve' : IDL.Nat,
  'imageId' : ExternalBlob,
});
export const Trade = IDL.Record({
  'tokenId' : IDL.Nat,
  'tradeType' : IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
  'trader' : IDL.Principal,
  'tokenAmount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'icpAmount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'buyTokens' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'createToken' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Nat],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getToken' : IDL.Func([IDL.Nat], [Token], ['query']),
  'getTokenBalance' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Nat], ['query']),
  'getTokenHolders' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Principal)], ['query']),
  'getTokenPrice' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getTokenTrades' : IDL.Func([IDL.Nat], [IDL.Vec(Trade)], ['query']),
  'getUserBalances' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTokens' : IDL.Func([], [IDL.Vec(Token)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listTokens' : IDL.Func([], [IDL.Vec(Token)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sellTokens' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Comment = IDL.Record({
    'tokenId' : IDL.Nat,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const Token = IDL.Record({
    'id' : IDL.Nat,
    'creator' : IDL.Principal,
    'ticker' : IDL.Text,
    'tokenSupply' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'icpReserve' : IDL.Nat,
    'imageId' : ExternalBlob,
  });
  const Trade = IDL.Record({
    'tokenId' : IDL.Nat,
    'tradeType' : IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
    'trader' : IDL.Principal,
    'tokenAmount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'icpAmount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'buyTokens' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'createToken' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Nat],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getToken' : IDL.Func([IDL.Nat], [Token], ['query']),
    'getTokenBalance' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [IDL.Nat],
        ['query'],
      ),
    'getTokenHolders' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getTokenPrice' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getTokenTrades' : IDL.Func([IDL.Nat], [IDL.Vec(Trade)], ['query']),
    'getUserBalances' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTokens' : IDL.Func([], [IDL.Vec(Token)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listTokens' : IDL.Func([], [IDL.Vec(Token)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sellTokens' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };