/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'tokenId' : bigint,
  'text' : string,
  'author' : Principal,
  'timestamp' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Token {
  'id' : bigint,
  'creator' : Principal,
  'ticker' : string,
  'tokenSupply' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'icpReserve' : bigint,
  'imageId' : ExternalBlob,
}
export interface Trade {
  'tokenId' : bigint,
  'tradeType' : { 'buy' : null } |
    { 'sell' : null },
  'trader' : Principal,
  'tokenAmount' : bigint,
  'timestamp' : bigint,
  'icpAmount' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'buyTokens' : ActorMethod<[bigint, bigint], bigint>,
  'createToken' : ActorMethod<[string, string, string, ExternalBlob], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getToken' : ActorMethod<[bigint], Token>,
  'getTokenBalance' : ActorMethod<[bigint, Principal], bigint>,
  'getTokenHolders' : ActorMethod<[bigint], Array<Principal>>,
  'getTokenPrice' : ActorMethod<[bigint], bigint>,
  'getTokenTrades' : ActorMethod<[bigint], Array<Trade>>,
  'getUserBalances' : ActorMethod<[], Array<[bigint, bigint]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTokens' : ActorMethod<[], Array<Token>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listTokens' : ActorMethod<[], Array<Token>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sellTokens' : ActorMethod<[bigint, bigint], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];